### ISSUE TITLE
roleplay 無法運行

### ISSUE THREAD

**Issue by allencyhsu** [bilibili/Index-1.9B#7]
roleplay 無法運行

下载以下模型到本地，并修改配置config/config.json

[bge-large-zh-v1.5](https://huggingface.co/BAAI/bge-large-zh-v1.5)
[Index-1.9B-Character](https://huggingface.co/IndexTeam/Index-1.9B-Character)

做完了，執行python hf_based_demo.py，出現以下錯誤

/home/allen/miniconda3/envs/index/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/allen/Projects/Index-1.9B/roleplay/hf_based_demo.py", line 27, in <module>
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
  File "/home/allen/miniconda3/envs/index/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 719, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "/home/allen/miniconda3/envs/index/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 497, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/allen/miniconda3/envs/index/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 199, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/home/allen/miniconda3/envs/index/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.IndexTeam.Index-1'

**Comment by BasicCoder** [comment]
You can refer to this solution #8

**Comment by allencyhsu** [comment]
> You can refer to this solution #8

yes, it's ok now.
